[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
lost-pixel = { path = "../lost-pixel" }
actix-web = "4"
actix-cors = "0.7.0"
clap = { version = "4.5.16", features = ["derive", "string"] }
figment = { version = "0.10.19", features = ["yaml", "env"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
mime_guess = "2.0.5"
rust-embed = "8.5.0"
open = "5.3.0"
